### PR TITLE
Update EV3 buttons

### PR DESCRIPTION
**Pull request by dwalton76**
From @ddemidov here
https://github.com/ev3dev/ev3dev/issues/957#issuecomment-328328952

### CODE REVIEW

**Comment by dwalton76** [comment]
Needed for https://github.com/rhempel/ev3dev-lang-python/issues/339

**Comment by WasabiFan** [comment]
I'd like to wait on this until we have our chat and work out the branching conventions in ev3dev-lang-python; once that happens, we can do the same thing here so that we separate out stretch changes from jessie.

**Comment by jabrena** [comment]
@dwalton76, @WasabiFan 

This change will appear in `ev3dev-stretch` isn´t it?

Juan Antonio

**Comment by dwalton76** [comment]
@jabrena yep this will be for stretch

@ddemidov are you ok with this one? I do not have merge permissions in this repo.

**Pull request merged**
