### PR TITLE
https://github.com/jabrena/ev3dev-lang-java/issues/6

### PR DESCRIPTION
**Pull request by jabrena**
Hi, this is my first pull request about the files which the content is generated by Autogen.

The file file: EV3DevConstants.java will be used by other Java classes.

This pull request is related with this issue:
https://github.com/jabrena/ev3dev-lang-java/issues/6

Cheers 

Juan Antonio

### CODE REVIEW

**Comment by rhempel** [comment]
@jabrena - we're going to skip this PR for now. Kernel release is coming up and I want to get the new `spec.json` as the baseline. Your API generator will likely need some minor adjustments.

**Comment by WasabiFan** [comment]
To be clear, we are interested in the library -- but it'd be best for us to wait a bit so that we can get the main repo updated and ready for kernel changes. I'd expect that these changes could require some changes on your end as well as we update the spec (but nothing too major, code-wise).

**Comment by rhempel** [comment]
Yes, we are definitely interested in the C# binding - sorry if that was not clear.

**Comment by jabrena** [comment]
@rhempel
Yes of course, when you release the new kernel, I will update the template development.

**Comment by dlech** [comment]
The kernel has been released. http://www.ev3dev.org/news/2015/12/15/Kernel-Release-Cycle-9/

**Comment by jabrena** [comment]
Fun this weekend!! 

This week, i read some new issues about motors. I will continúe with testing. I will make some questions.

Cheer mates.

Juan Antonio

**Comment by jabrena** [comment]
Hi @dlech,

is the package available to upgrade in the brick to continue testing?

**Comment by dlech** [comment]
Yes. `sudo apt-get update; sudo apt-get upgrade; sudo apt-get dist-upgrade`.

**Comment by WasabiFan** [comment]
@jabrena We recently changed the structure of our repo to make it so that, aside from adding your language to the list of language comment formats, you don't have to modify the main repo to be able to add and autogen your code. See #142 for more information.

**Comment by jabrena** [comment]
@WasabiFan Oki

I am going to close this pull request and follow the notes from #142

**Pull request closed without merging**
